declare module 'react-actioncable-provider'
declare module 'react-router-dom'
declare module 'chess.js'
declare module 'chessboardjsx'
declare module 'action-cable'
declare module 'react-expand-animated'
declare module 'react-chessground'